{
 "title": "Overmind",
 "tags": [ "screeps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "colonies", "label": "Colonies", "query": "stats.gauges.colonies.*" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(movingAverage(stats.gauges.cpu.getUsed, 5), #B)",
     "targetFull": "asPercent(movingAverage(stats.gauges.cpu.getUsed, 5), stats.gauges.cpu.limit)"
    }
   ]
  },
  {
   "title": "CPU / Bucket / Resets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(stats.gauges.cpu.getUsed, 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(movingAverage(stats.gauges.cpu.getUsed, '5min'), 'Average CPU')"
    },
    {
     "target": "alias(stats.gauges.cpu.limit, 'Limit')"
    },
    {
     "target": "alias(scale(derivative(stats.gauges.persistent.lastGlobalReset), 10000), 'Global Reset')"
    },
    {
     "target": "alias(scale(derivative(stats.gauges.persistent.lastMemoryReset), 10000), 'Memory Reset')"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.cpu.bucket" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.memory.used" }
   ]
  },
  {
   "title": "IVM Heap Statistics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(exclude(keepLastValue(stats.gauges.cpu.heapStatistics.*, 500), 'does_zap_garbage'), 4)"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(stats.gauges.gcl.progress, #B)",
     "targetFull": "asPercent(stats.gauges.gcl.progress, stats.gauges.gcl.progressTotal)"
    }
   ]
  },
  {
   "title": "Expansion Ranking",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.gcl.level" }
   ]
  },
  {
   "title": "GCL Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(stats.gauges.gcl.progress, 100)), 10), 86400), 'GCL / 24hr')"
    },
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(stats.gauges.gcl.progress, 100)), 500), 86400), 'GCL / 24hr (avg)')"
    }
   ]
  },
  {
   "title": "GCL by Colony",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(stats.gauges.colonies.$colonies.rcl.progress, 100)), 3600), 86400)), 3)"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Rem')",
     "targetFull": "alias(divideSeries(alias(keepLastValue(diffSeries(stats.gauges.gcl.progressTotal, stats.gauges.gcl.progress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(stats.gauges.gcl.progress)), 500), 86400), 'GCL / 24hr (avg)')), 'Rem')"
    }
   ]
  },
  {
   "title": "Colonies Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "rooms",
   "targets": [
    {}
   ]
  },
  {
   "title": "DEFCON Levels",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(stats.gauges.colonies.*.defcon), 3)"
    }
   ]
  },
  {
   "title": "Hatchery Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(stats.gauges.colonies.$colonies.hatchery.uptime), 3)"
    }
   ]
  },
  {
   "title": "RCL Progress Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(scale(movingAverage(perSecond(keepLastValue(stats.gauges.colonies.$colonies.rcl.progress)), 200), 86400), 3)"
    }
   ]
  },
  {
   "title": "Lab uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(stats.gauges.colonies.$colonies.evolutionChamber.avgUsage, 500), '1hour'), 3)"
    }
   ]
  },
  {
   "title": "Average Barrier Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(stats.gauges.colonies.*.avgBarrierHits, 100), 3)"
    }
   ]
  },
  {
   "title": "Energy Assets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(stats.gauges.colonies.$colonies.assets.energy, 100), 3)"
    }
   ]
  },
  {
   "title": "Average MiningSite Usage/Downtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(stats.gauges.colonies.$colonies.miningSites.avgUsage, 100), '30min'), 3), \"(.*)\", \"Usage - \\1\")"
    },
    {
     "target": "aliasSub(aliasByNode(keepLastValue(stats.gauges.colonies.$colonies.miningSites.avgDowntime, 100), 3), \"(.*)\", \"Downtime - \\1\")"
    }
   ]
  },
  {
   "title": "Energy Income Per Tick",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(stats.gauges.colonies.$colonies.miningSites.energyInPerTick, 500), '30min'), 3)"
    }
   ]
  },
  {
   "title": "Terminal Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Global Mineral Assets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "exclude(aliasByNode(#A, 0), \"energy\")",
       "targetFull": "exclude(aliasByNode(groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.*, 500), \"sum\", 5), 0), \"energy\")"
      }
     ]
    },
    {
     "title": "Global T3 Assets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XGH2O, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XGHO2, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XKH2O, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XKHO2, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XLH2O, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XLHO2, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XUH2O, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XUHO2, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XZH2O, 500), 'sum', 5)"
      },
      {
       "target": "groupByNodes(keepLastValue(stats.gauges.colonies.*.assets.XZHO2, 500), 'sum', 5)"
      }
     ]
    },
    {
     "title": "Compound Production/Consumption",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(derivative(exclude(#A, '^(energy|H|O|U|K|L|Z|X)$')), '2hour'), 0)",
       "targetFull": "aliasByNode(movingAverage(derivative(exclude(groupByNodes(removeBelowValue(keepLastValue(stats.gauges.colonies.*.assets.*, 500), 0), \"sum\", 5), '^(energy|H|O|U|K|L|Z|X)$')), '2hour'), 0)"
      }
     ]
    },
    {
     "title": "Energy Transfer Rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 500)"
      }
     ]
    },
    {
     "title": "Incoming Energy Rate",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), '24hour'), 86000)), 0)"
      }
     ]
    },
    {
     "title": "Incoming Energy per 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), 500), 86000), 0)"
      }
     ]
    },
    {
     "title": "Fractional Energy Transfer Cost",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(stats.gauges.persistent.terminalNetwork.transfers.costs.*.*))), 86400), 200), movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 200))"
      }
     ]
    },
    {
     "title": "Outgoing Energy Rate",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), '24hour'), 86000)), 0)"
      }
     ]
    },
    {
     "title": "Outgoing Energy per 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(stats.gauges.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), 500), 86000), 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Trade Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Credits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.persistent.trader.credits"
    }
   ]
  },
  {
   "title": "Resource Transactions per 24h (Amounts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(perSecond(movingAverage(keepLastValue(stats.gauges.persistent.trader.bought.*.amount), 100)), 86000),5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(perSecond(movingAverage(keepLastValue(stats.gauges.persistent.trader.sold.*.amount), 100)), -86000),5)"
    }
   ]
  },
  {
   "title": "Resource Transactions per 24h (Credits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(perSecond(movingAverage(keepLastValue(stats.gauges.persistent.trader.bought.*.credits), 100)), 86000),5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(perSecond(movingAverage(keepLastValue(stats.gauges.persistent.trader.sold.*.credits), 100)), -86000),5)"
    }
   ]
  },
  {
   "title": "ΔCredits / 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scaleToSeconds(perSecond(keepLastValue(stats.gauges.persistent.trader.credits, 500)), 86400)"
    }
   ]
  }
 ]
}